---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "demo-spanner-jdbc-web-sp"
  namespace: "trial"
  labels:
    app: "demo-spanner-jdbc-web-sp"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: "demo-spanner-jdbc-web-sp"
  template:
    metadata:
      labels:
        app: "demo-spanner-jdbc-web-sp"
    spec:
      containers:
      - name: "demo-spanner-jdbc-web-sp"
        image: "gcr.io/turnkey-rookery-323304/demo-spanner-jdbc-web:latest"
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "spanner-gcp"
  serviceAccountName: ksa_trial

---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "demo-spanner-jdbc-web-sp-service"
  namespace: "trial"
  labels:
    app: "demo-spanner-jdbc-web-sp"
    app.kubernetes.io/managed-by: "gcp-cloud-build-deploy"
spec:
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 8080
  selector:
    app: "demo-spanner-jdbc-web-sp"
  type: "LoadBalancer"
  serviceAccountName: ksa_trial
---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    iam.gke.io/gcp-service-account: gsa-trial@turnkey-rookery-323304.iam.gserviceaccount.com
  name: ksa-trial
  namespace: trial