---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "demo-spanner-jdbc-web"
  namespace: "default"
  labels:
    app: "demo-spanner-jdbc-web"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "demo-spanner-jdbc-web"
  template:
    metadata:
      labels:
        app: "demo-spanner-jdbc-web"
    spec:
      containers:
      - name: "demo-spanner-jdbc-web"
        image: "gcr.io/turnkey-rookery-323304/demo-spanner-jdbc-web:latest"
        ports:
        - containerPort: 80
---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "demo-spanner-jdbc-web-service"
  namespace: "default"
  labels:
    app: "demo-spanner-jdbc-web"
    app.kubernetes.io/managed-by: "gcp-cloud-build-deploy"
spec:
  ports:
  - protocol: "TCP"
    port: 80
  selector:
    app: "demo-spanner-jdbc-web"
  type: "LoadBalancer"
        