steps:

  # build the container image with maven
- name: maven:3-jdk-11
  entrypoint: mvn
  args:
  - spring-boot:build-image
  - -Dspring-boot.build-image.imageName=gcr.io/turnkey-rookery-323304/demo-spanner-jdbc-web

  # push container image
- name: "gcr.io/cloud-builders/docker"
  args:
  - push
  - gcr.io/turnkey-rookery-323304/demo-spanner-jdbc-web

  # deploy container image to GKE
- name: "gcr.io/cloud-builders/gke-deploy"
  args:
  - run
  - --filename=deployment/deployment-spanner.yml
  - --location=asia-northeast1-a
  - --cluster=gke-trial